// <auto-generated />
namespace Demo.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Student_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "201610010655350_Student_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
